### ISSUE TITLE
setup do not automatically install higlass-python

### ISSUE THREAD

**Issue by gpolles** [higlass/higlass-manage#17]
When installing via pip, higlass-python is not automatically installed, raising a
ModuleNotFoundError: No module named 'higlass'
when trying to run it.

**Comment by pkerpedjiev** [comment]
Thanks for pointing this out! I think it's fixed in the master branch and will be in the next release.

**Comment by flekschas** [comment]
https://github.com/higlass/higlass-manage/blob/5aeddf00ccad06ca9afc5c27a43f29db83984529/requirements.txt#L2 :heavy_check_mark:
