### ISSUE TITLE
Error retrieving tilesetInfo from: /api/v1

### ISSUE THREAD

**Issue by dphansti** [higlass/higlass-manage#19]
I am trying to view a data made by Juicer.  I converted the hic file to cool using hic2cool which appeared to work.

```hic2cool inter_30.hic test.cool -r 10000
################
### hic2cool ###
################
hic file header info:
Chromosomes:  ['ALL', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y', 'MT']
Resolutions:  [2500000, 1000000, 500000, 250000, 100000, 50000, 25000, 10000, 5000]
Genome:  hg19
Resolution 10000 took: 1111.847009897232 seconds.
hic2cool is finished! Output written to: test.cool
```

But when I run 
```higlass-manage view test.cool``` 
or 
```higlass-manage start```
```higlass-manage ingest test.cool ```
```higlass-manage browse```

and try to load my file it says 'loading' for a long time and then eventually 'Error retrieving tilesetInfo from: /api/v1'

Loading other public files works fine.

**Comment by pkerpedjiev** [comment]
Hey, thanks for reporting! Would you mind sharing `test.cool`?

**Comment by dphansti** [comment]
Sure.  Do you have a suggested method for sharing it?  It is 858MB.  Thanks

**Comment by dphansti** [comment]
Nevermind.  You can get it here.

http://phanstiel-lab.med.unc.edu/data/test.cool

**Comment by pkerpedjiev** [comment]
Thanks for sharing that. It doesn't look like all the resolutions were extracted from the .hic file:

![image](https://user-images.githubusercontent.com/2143629/51700008-1e1d1780-1fdc-11e9-9978-63508b24160a.png)

Normally there would be a group called `resolutions`

Can you post the command line you used to do the conversion? @carlvitzthum and @nvictus, any other ideas?

**Comment by pkerpedjiev** [comment]
Here's the log from the server:

```
  File "/opt/conda/lib/python3.6/site-packages/clodius/tiles/cooler.py", line 520, in tileset_info
    (f, info) = make_mats(filepath)
  File "/opt/conda/lib/python3.6/site-packages/clodius/tiles/cooler.py", line 487, in make_mats
    info = get_info(filepath)
  File "/opt/conda/lib/python3.6/site-packages/clodius/tiles/cooler.py", line 175, in get_info
    'The `max_zoom` attribute is missing.'
ValueError: The `max_zoom` attribute is missing.
```

**Comment by carlvitzthum** [comment]
A couple issues here:
- The `resolutions` group should be populated by hic2cool, but it hasn't been updated in ~7 months and I believe some significant changes have been made to cooler in that time.
- `max_zoom` is currently not written by hic2cool. I started an implementation for that and cam finish it in the next release.

@dphansti Could you let me know what version of cooler you used?

**Comment by carlvitzthum** [comment]
Okay, if you ran with a single resolution, then it makes sense that the `resolutions` group would be missing. higlass is only compatible with multi-resolution files (obtained by running hic2cool with `-r 0` or omitting the argument).

However, this will not fix the issue since hic2cool does not currently add the `max_zoom` attribute which is required by the current version of cooler (and thus higlass). I will be working on a update to fix this in the near future and will let you know when it's finished.

**Comment by dphansti** [comment]
Great.  Thanks so much.  I am looking forward to it.

**Comment by pkerpedjiev** [comment]
@dphansti If you do convert it using all the resolutions, would you mind posting a link to the output file? I can try a parallel approach to load it into higlass while Carl's  working on hic2cool.

**Comment by dphansti** [comment]
@pkerpedjiev Here you go
http://phanstiel-lab.med.unc.edu/data/test2.multi.cool

**Comment by pkerpedjiev** [comment]
@dphansti That dataset works for me, no modifications needed :)

![image](https://user-images.githubusercontent.com/2143629/51717532-3195a600-200f-11e9-9b8a-53b7e5be0581.png)

**Comment by dphansti** [comment]
Yep.  This works for me as well.  Thanks!
