### ISSUE TITLE
Redis config missing

### ISSUE THREAD

**Issue by keiranmraine** [higlass/higlass-manage#32]
The docs state that redis should work out of the box:

higlass-manage ingest --project-name Dovetail-data --name WTSI-OESO_103 raw-data/WTSI-OESO_103.mcool

I've had to run the following pulling the config from the docker repo:

```
pip3 install higlass-manage
mkdir /home/ubuntu/.local/lib/python3.6/site-packages/higlass_manage/redis
curl -L https://raw.githubusercontent.com/higlass/higlass-docker/master/redis-context/redis.conf > /home/ubuntu/.local/lib/python3.6/site-packages/higlass_manage/redis/redis.conf
```

**Comment by alexpreynolds** [comment]
In theory, use of `setup.py` to install `higlass-manage` should copy over a `redis.conf` file:

https://github.com/higlass/higlass-manage/blob/master/setup.py#L12

Are you using `setup.py` or another procedure to install things?

**Comment by alexpreynolds** [comment]
Also, are you use `--use-redis` when `start`-ing a HiGlass server? The command you used ingests a dataset but does not start a server, so I'm a little confused about that. Redis helps the server with data caching, but I don't believe it plays any role in data ingestion.

**Comment by keiranmraine** [comment]
As shown above, I used pip3 `install higlass-manage`.  I didn't show the start command.  This is what I use:

```
higlass-manage start --port 8888 --site-url 172.27.81.12 --use-redis
```

(I raised a separate issue about duplicated ingest, which may have caused cross-confusion)

**Comment by alexpreynolds** [comment]
To perhaps help isolate the problem, does the `--use-redis` option work with your custom Conda or other Python environment, after using `python setup.py install` to install `higlass-manage`, instead of `pip3`?

**Comment by keiranmraine** [comment]
This is not being executed on a host with the custom conda/pip or virtual env.

I created a clean ubuntu VM, installed py3 packages and ran:

```
$ pip3 install higlass-manage
$ higlass-manage start --port 8888 --site-url 172.27.81.12 --use-redis
Pulling redis:5.0.3-alpine
done
Error: Could not locate Redis configuration file [/home/ubuntu/.local/lib/python3.6/site-packages/higlass_manage/redis/redis.conf]
```

To reproduce on a system where the redis file has been put in place by an earlier installation:

```
$ pip3 uninstall higlass-manage
$ rm -f /home/ubuntu/.local/lib/python3.6/site-packages/higlass_manage/redis/redis.conf
$ pip3 install higlass-manage
$ higlass-manage start --port 8888 --site-url 172.27.81.12 --use-redis
Pulling redis:5.0.3-alpine
done
Error: Could not locate Redis configuration file [/home/ubuntu/.local/lib/python3.6/site-packages/higlass_manage/redis/redis.conf]
```

Fix by running:

```
$ mkdir /home/ubuntu/.local/lib/python3.6/site-packages/higlass_manage/redis
$ curl -L https://raw.githubusercontent.com/higlass/higlass-docker/master/redis-context/redis.conf > /home/ubuntu/.local/lib/python3.6/site-packages/higlass_manage/redis/redis.conf
$ higlass-manage start --port 8888 --site-url 172.27.81.12 --use-redis
Attempting to remove existing Docker network instance
Pulling redis:5.0.3-alpine
done
Pulling latest image... 
done
Data directory: /home/ubuntu/hg-data
...
```

**Comment by alexpreynolds** [comment]
To troubleshoot this, I first tested out using the `python3 setup.py install` procedure.

On a stock Ubuntu 16 host (t2.micro AWS host), some setup of development tools and libraries used for dependencies:

```
$ sudo apt install gcc
$ sudo apt install zlib1g-dev
$ sudo apt-get install libpng-dev
$ sudo apt install libssl1.0-dev
$ sudo apt-get install python3-dev
$ sudo apt-get install linux-headers-$(uname -r) build-essential
```

Install Docker for Ubuntu:  https://docs.docker.com/install/linux/docker-ce/ubuntu/

Setup Docker group membership and service: https://docs.docker.com/install/linux/linux-postinstall/

In a Python environment, install `higlass-manage`:

```
$ python3 -m venv env
$ source env/bin/activate
(env) $ git clone https://github.com/higlass/higlass-manage
(env) $ cd higlass-manage
(env) $ python3 setup.py install
```

Start a higlass server with Redis support:

```
$ higlass-manage start --port 80 --site-url 18.221.202.66 --use-redis
Pulling redis:5.0.3-alpine
done
Pulling latest image... 
done
Data directory: /home/ubuntu/hg-data
Temp directory: ()
Starting... default 80
Docker started: higlass-manage-container-default
sending request 1
Waiting to start (tilesets)...
sending request 2
Waiting to start (tilesets)...
sending request 3
Waiting to start (tilesets)...
sending request 4
Waiting to start (tilesets)...
sending request 5
Waiting to start (tilesets)...
sending request 6
Non 200 status code returned (502), waiting...
sending request 7
Non 200 status code returned (502), waiting...
sending request 8
Non 200 status code returned (502), waiting...
sending request 9
Non 200 status code returned (502), waiting...
sending request 10
Non 200 status code returned (502), waiting...
sending request 11
Non 200 status code returned (502), waiting...
sending request 12
Non 200 status code returned (502), waiting...
sending request 13
Non 200 status code returned (502), waiting...
sending request 14
Non 200 status code returned (502), waiting...
sending request 15
public_data: True
Replaced js file
Started 
```

Open the higlass client: http://18.221.202.66

```
(env) $ higlass-manage stop
```

So that approach works.

It does look like use of `pip3` does not work in its own test environment:

```
(env-pip3) $ higlass-manage start --port 80 --site-url 18.221.202.66 --use-redis
Pulling redis:5.0.3-alpine
done
Error: Could not locate Redis configuration file [/home/ubuntu/env2/lib/python3.6/site-packages/higlass_manage/redis/redis.conf]
```

I'm not 100% positive, but it _might_ be that a `MANIFEST.in` file is also needed to bring in the Redis configuration file: https://docs.python.org/2/distutils/sourcedist.html#manifest-template

Pete may have a preferred solution for this.

**Comment by pkerpedjiev** [comment]
Just cut a new release (v0.7.2) that include the `redis.conf` file. @keiranmraine would you mind trying it out again with the new version and seeing if that works better for you?

**Comment by keiranmraine** [comment]
Yes I can confirm this works as expected.
