### ISSUE TITLE
no vertical scrollbar in v0.6.34

### ISSUE THREAD

**Issue by annashcherbina** [higlass/higlass-manage#49]
![image](https://user-images.githubusercontent.com/5261545/69270245-6e76ee80-0b87-11ea-8279-878af1bd00e3.png)

^ I am using Chrome to view the tracks. The tracks below the view window are not accessible for view (i.e. there is no vertical scrollbar)

**Comment by flekschas** [comment]
Hi Anna, sorry for our late response and thanks for reaching out. Just to document our Slack conversation:

Vertical scrolling is currently a developer-only feature and hasn't made it into the UI. Having said that, we're planning to add support for it through [higlass-app](https://github.com/higlass/higlass-app), which is the application wrapper for the JavaScript library.

How would you imagine to switch from panning&zomming to scrolling? We could use some kind of kay modifier to activate it (e.g., click and hold ALT to scroll with the mouse wheel. I guess the scrollbar should be visible and usable at all times to provide a visual indicator that one can scroll in general.

**Comment by annashcherbina** [comment]
Hi Fritz, 
Click and hold ALT to scroll with mouse wheel sounds fine to me. 
Yes, having a scroll bar constantly visible would be great (or alternatively have a tooltip that indicates how the scrollbar can be made visible). 
Thanks! I will wait for this feature in higlass-app.

**Comment by flekschas** [comment]
I've created a ticket over here: https://github.com/higlass/higlass-app/issues/14
I hope to get to it in the near future :)
