### ISSUE TITLE
old viewconf-s not working after migrating higlass instance

### ISSUE THREAD

**Issue by sergpolly** [higlass/higlass-manage#53]
- context:
we had a local higlass on 1 machine (with a lot of things ingested) - now we need to move it to a new computer (different network). Ideally such that everything would remain functional, including saved viewconf-s.

 - what we do:
grab an existing `db.sqlite` along with `hg-data` folder - copy those to a new computer, relaunch higlass-docker container with `--hg-data` pointing to the copied `hg-data` folder. Done! - everything works, ingested data is there. but ...

 - problem:
of course viewconf-s saved in the database point to previous location for most of the tilesets. So, if we shut down the old machine viewconfs would stop working ...

 - question:
is there a script/pulg-in/tutorial for migrating a higlass ?
if not, would it be cool to have one ? as part of `higlass-manage` ?
would a solution based on manual sqlite's database `UPDATE ... table ... replace` be ok e.g. https://stackoverflow.com/questions/10532656/sqlite-replace-part-of-a-string   ?

**Comment by pkerpedjiev** [comment]
Good questions!

> is there a script/pulg-in/tutorial for migrating a higlass ?

Not currently.

> if not, would it be cool to have one ? as part of higlass-manage ?

Yes. But the first step it should do is back up the old database.

> would a solution based on manual sqlite's database UPDATE ... table ... replace be ok e.g. https://stackoverflow.com/questions/10532656/sqlite-replace-part-of-a-string ?

I think that would be fine.

**Comment by sergpolly** [comment]
yay ! finally submitted a PR - but it's WIP - "in progress" , mostly because there is a nice and native way to backup sqlite in python>=3.7 - which would be to limiting to require I feel like - so what do we do about it ?...

also - more "philosophical" question - is there any way to make those `tileset`-URLs in the `viewconf` relative ? just to avoid the whole migration thing with replacing `origin` to `destination`... I don't really know much about web, so not sure if relative URL is even a thing, ... also PORT  messes things up, i guess
