### ISSUE TITLE
Empty view fresh install

### ISSUE THREAD

**Issue by jakevc** [higlass/higlass-manage#58]
With higlass-manage I have a blank view when I try and run a fresh container. I ran higlass-manage start, and I was able to ingest a tileset. The server is running where it should, but my empty higlass page looks more empty than I expect.

![Screen Shot 2020-05-06 at 3 42 55 PM](https://user-images.githubusercontent.com/17414791/81235814-b1e7dc80-8fb0-11ea-8f70-f9e28081b2df.png)

I am able to right click and add rulers but there is not header for the container with the cog for editing a viewconf. 
![Screen Shot 2020-05-06 at 3 44 12 PM](https://user-images.githubusercontent.com/17414791/81235853-c7f59d00-8fb0-11ea-8657-9d5537daa578.png)

Also, higlass-manage doesn't have a "log" subcommand like the documentation says.. 

I am running higlass-manage 0.8.0

**Comment by jakevc** [comment]
Ahh I just dragged a viewconf in there and it work...

**Comment by pkerpedjiev** [comment]
Hey, glad you got it working. It sounds like the viewconf that was loaded before had `editable: false` set to hide the header.

As for the `log` command, it's actually `higlass-manage logs`. Sorry about that. I updated the docs to match.
