### ISSUE TITLE
I cannot install it

### ISSUE THREAD

**Issue by mannekim** [higlass/higlass-manage#78]
Hi,
I am on windows
i have python 3.10.2

i could not install it successfully
i get a really long error message

![image](https://user-images.githubusercontent.com/44848241/156375594-10b801af-1caa-49ba-88b0-7569bd023e25.png)

**Comment by nvictus** [comment]
higlass-manage isn't supported natively on Windows. However, it should be possible to install in the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about). Note that this solution will also require installing the WSL2 Docker [backend](https://docs.docker.com/desktop/windows/wsl/).

**Comment by pkerpedjiev** [comment]
I don't see the image on there. Any chance you could repost it?
