### ISSUE TITLE
Local Tilesets not loading

### ISSUE THREAD

**Issue by corinsexton** [higlass/higlass-manage#85]
Hi there.

I'm running up against an issue where my docker instance and app starts just fine but none of my local tilesets are available for viewing. They are showing up in admin and the files are in the `~/hg-data/media/uploads/` directory. However when I click in the admin view on one of the tilesets it says:

```Tileset with ID <id here> doesn't exist. Perhaps it was deleted?```

Starting with `higlass-manage` start gives me this message:

```
Pulling latest image...
done
Data directory: ~/hg-data
Temp directory: ()
Starting... default 8989
Docker started: higlass-manage-container-default
sending request 1
Waiting to start (tilesets)...
sending request 2
Waiting to start (tilesets)...
sending request 3
Waiting to start (tilesets)...
sending request 4
Waiting to start (tilesets)...
sending request 5
Non 200 status code returned (502), waiting...
sending request 6
Non 200 status code returned (502), waiting...
sending request 7
...
Non 200 status code returned (502), waiting...
sending request 27
Request timed out
sending request 28
Request timed out
sending request 29
Request timed out
sending request 30
Request timed out
sending request 31
public_data: True
Replaced js file
Started
```

I'm on M2 MacBook macOS12.6 using Docker desktop. This was working back in November and was broken when I booted it back up today.

Thanks for any help.

**Comment by pkerpedjiev** [comment]
I'm guessing that in the admin view you're clicking on the "datafile" column? Would you mind clicking on the date in the "Created" column instead?

**Comment by corinsexton** [comment]
Everything looks good here.

<img width="1375" alt="Screen Shot 2023-01-23 at 9 45 52 PM" src="https://user-images.githubusercontent.com/13277644/214220821-e05868f8-6e16-49ee-90dd-e1b94cf70581.png">

**Comment by pkerpedjiev** [comment]
Great! Does that solve your issue or was there something else I could help with?

**Comment by corinsexton** [comment]
Looks like it's all working now. Still don't know why it wouldn't let me see the tilesets in the viewer before, but I'm glad it's working as expected. Thanks for the help.
